from __future__ import annotations

from dataclasses import dataclass


@dataclass
class ReportGenerationResult:
    report: str
    truncated: bool
    warning: str | None


class MockReportService:
    def generate_report(self, diagnosis: str, confidence_score: float, patient_id: str, filename: str) -> ReportGenerationResult:
        warning = None
        report = "\n".join(
            [
                "Findings are generated by a mock AI workflow for review support.",
                f"Model confidence: {confidence_score:.0%}.",
                f"Impression: {diagnosis}.",
                "Recommend correlation with clinical symptoms and radiologist confirmation.",
                f"Series: {patient_id}/{filename}.",
            ]
        )

        if confidence_score < 0.5:
            warning = "limited confidence"
            report = f"limited confidence\n{report}"

        return ReportGenerationResult(report=report, truncated=False, warning=warning)


_service = MockReportService()


def get_gpt_service() -> MockReportService:
    return _service
